# -*- coding: utf-8 -*-
"""Chapter_35_Hands_on_MLR_2_babystep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198XgFxkqclNvIU_bf65NBBQujbAEMKeA
"""

import pickle
load_model=pickle.load(open("Multiple_Linear_Model.sav","rb"))
load_model.predict([[165349.2,136897.8,	471784.1,0,1]])