# -*- coding: utf-8 -*-
"""Chapter_29_How_to_do_Assignment_Baby_Step_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7TX0H7hhCEQxAG6SEWWMhDFVyylWhjp
"""

# This Library is used for handle the csv files
import pandas as pd
# This Library is Used for creating graphs and visualizations.
import matplotlib.pyplot as plt
# Reads the CSV file in table format
data = pd.read_csv('Salary_Data.csv')
# display the data which we read from the above csv to confirm the reading gone fine.
data

#In the below step we split the data and have only the independant column from the above mentioned csv file. in our case only one column
independent = data[["YearsExperience"]]
#In the below step we split the data and have only the dependent  column from the above mentioned csv file. in our case only one column
dependent = data[["Salary"]]

#Creates a scatter plot using the independent variable on the x-axis and the dependent variable on the y-axis.
plt.scatter(independent,dependent)
# Adds a label to the x-axis and set the font size
plt.xlabel('YearsExperience',fontsize=20)
# Adds a label to the y-axis and set the font size
plt.ylabel('Salary',fontsize=20)
# Displays the plot on the screen. Based on this chart only we need to decide what kind of algo we have to use
#in our case as it is kind of line we decide to use linear algorithm and as it is one input and one output
#we decide to go with simple linear regression algo
plt.show()

# Imports the train_test_split function from scikit-learn package and model_selection.py file under that.
from sklearn.model_selection import train_test_split
# Splits the independent and dependent variables into training and test sets. we are keeping 70% data for training and 30% for test
#X_train is for training, X_test for testing , y_train for training , y_test to validate our model result gainst this set while testing
#to calculate the R square value
X_train, X_test, y_train, y_test = train_test_split(independent,dependent, test_size = 0.30, random_state = 0)

# Imports the LinearRegression class from scikit-learn package and linear_model py file under that
from sklearn.linear_model import LinearRegression
#Creates an object called 'regressor' from the LinearRegression class.
regressor = LinearRegression()
#call the Fit function under that class. Once this run means the training got over. Once this run means model is done. As slope
#and intercept we have found it means model is done
regressor.fit(X_train, y_train)

# this is slope
weight=regressor.coef_
print("Weight of the model={}".format(weight))
# this is bais, or inital value or intercept
bais=regressor.intercept_
print("Intercept of the model={}".format(bais))

#As training got over, we will do testing to see the quality of learning
y_pred=regressor.predict(X_test)

#Import r2_score function from the package r2_score and metrics py file under that
from sklearn.metrics import r2_score
# To Calculate the quality we need to give the model test output and raw file orginal test set value. If both match to the dot it
#it is 100% best model, but practically we will not get 100%, but anything close to 100 will be consider good model
#in out case 97% which is a good model
r_score=r2_score(y_test,y_pred)
#display rscore value
r_score

# Pickle is used to save the trained model in a file so that every time we dont want to train it, instead we can import this saved file
#and run the model
import pickle

filename = 'finalized_model.sav'
#write the trained model in a file
pickle.dump(regressor, open(filename, 'wb'))

#to test we load the saved model
loaded_model = pickle.load(open('finalized_model.sav', 'rb'))
#pass 15 as input and see the result
result = loaded_model.predict([[15]])
print(result)