# -*- coding: utf-8 -*-
"""Chapter_35_Hands_on_MLR_2_MainCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLQ3YCG9fDcsWQg88Ral365H1sHYuw8l
"""

import pandas as pd
dataset=pd.read_csv("50_Startups.csv")
dataset
dataset.columns
dataset=pd.get_dummies(dataset,drop_first=True)
dataset.columns
independant=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependant=dataset[['Profit']]
dependant=dataset[['Profit']]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
print(regressor.coef_)
print (regressor.intercept_)
y_pred=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score
regressor.predict([[165349.2,136897.8,	471784.1,0,1]])
import pickle
pickle.dump(regressor,open("Multiple_Linear_Model.sav","wb"))

loaded_model=pickle.load(open("Multiple_Linear_Model.sav","rb"))
loaded_model.predict([[165349.2,136897.8,	471784.1,0,1]])